

ln -s /usr/local/clas-software/reconstruction/ana
ln -s /usr/local/clas-software/io/bankdefs
ln -s /usr/local/clas-software/io/bos
ln -s /usr/local/clas-software/io/bosio
ln -s /usr/local/clas-software/io/caldb
ln -s /usr/local/clas-software/io/c_bos_io
ln -s /usr/local/clas-software/detector/cc
ln -s /usr/local/clas-software/reconstruction/c_cern
ln -s /usr/local/clas-software/build/bin/ced
ln -s /usr/local/clas-software/analysis/ClasTool
ln -s /usr/local/clas-software/io/clasutil
ln -s /usr/local/clas-software/io/c_sql
ln -s /usr/local/clas-software/detector/dc
ln -s /usr/local/clas-software/detector/ec
ln -s /usr/local/clas-software/reconstruction/eloss
ln -s /usr/local/clas-software/reconstruction/epics
ln -s /usr/local/clas-software/io/fdump
ln -s /usr/local/clas-software/io/fpack
ln -s /usr/local/clas-software/io/fputil
ln -s /usr/local/clas-software/reconstruction/gem
ln -s /usr/local/clas-software/build/bin/gpp
ln -s /usr/local/clas-software/simulation/gsim
ln -s /usr/local/clas-software/build/bin/gsim_bat
ln -s /usr/local/clas-software/build/bin/gsim_int
ln -s /usr/local/clas-software/analysis/ced/Hv
ln -s /usr/local/clas-software/detector/icf
ln -s /usr/local/clas-software/analysis/ClasTool/include
ln -s /usr/local/clas-software/detector/lac
ln -s /usr/local/clas-software/analysis/ClasTool/Makefile
ln -s /usr/local/clas-software/io/Map
ln -s /usr/local/clas-software/analysis/ClasTool/Makefile
ln -s /usr/local/clas-software/io/Map
ln -s /usr/local/clas-software/build/bin/n10maker
ln -s /usr/local/clas-software/reconstruction/online_dummy
ln -s /usr/local/clas-software/build/bin/pdu
ln -s /usr/local/clas-software/reconstruction/pid
ln -s /usr/local/clas-software/reconstruction/recsis
ln -s /usr/local/clas-software/reconstruction/scaler
ln -s /usr/local/clas-software/reconstruction/scat
ln -s /usr/local/clas-software/analysis/ClasTool/scripts
ln -s /usr/local/clas-software/reconstruction/seb
ln -s /usr/local/clas-software/detector/sh
ln -s /usr/local/clas-software/detector/st
ln -s /usr/local/clas-software/detector/tag
ln -s /usr/local/clas-software/reconstruction/trk
ln -s /usr/local/clas-software/reconstruction/user
ln -s /usr/local/clas-software/build/bin/user_ana
ln -s /usr/local/clas-software/io/Map/utilities
ln -s /usr/local/clas-software/reconstruction/vertex
